import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";

import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  display: 'swap',
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  display: 'swap',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Alah Author Bacot",
  description: "Generated by Autho Tolol",
  openGraph: {
    title: 'Web Kebacotan Author Tolol',
    description: 'Ga jelas webnya,skip aja',
    url: 'https://taksi-xmlbb.vercel.app',
    siteName: 'Lawak bcot',
    locale: 'id_ID',
    type: 'website'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full">{children}
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
